### ISSUE TITLE
Update module-consul to be compatible with latest Consul API version

### ISSUE THREAD

**Issue by Ibaqu** [wso2-ballerina/module-consul#46]
**Description:**
Module is no longer compatible with the latest Consul API Version. This requires and update.
Currently module-consul is compatible with Consul API Version 1.0.0

**Suggested Labels:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Comment by anupama-pathirage** [comment]
Closing as we are no longer maintaining this code.
